spring.application.name=rider-companion
spring.datasource.url=jdbc:postgresql://localhost:5432/rider_companion
spring.datasource.username=postgres
spring.datasource.password=oussama21092004

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
server.port=8081
server.forward-headers-strategy=framework

# OpenAPI JSON: /v3/api-docs | Swagger UI: /swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui.html
spring.profiles.active=local