import { useState } from 'react';
import { Button, Platform, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { mobileAuthApi } from '../src/api';
import { useSession } from '../src/session';
export default function AuthScreen() {
 const {setSession}=useSession(); const [register,setRegister]=useState(false); const [firstName,setFirstName]=useState(''); const [lastName,setLastName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const submit=async()=>{setError(''); if(!email.includes('@')||password.length<8|| (register&&(!firstName.trim()||!lastName.trim()))) return setError('Enter a valid email, an 8-character password, and your name.'); setBusy(true); try { const metadata={email,password,deviceName:'Rider Companion',platform:Platform.OS,appVersion:'beta'}; const session=register ? await mobileAuthApi.register({firstName,lastName,credentials:metadata}) : await mobileAuthApi.login(metadata); await setSession(session); router.replace('/(tabs)'); } catch(e:any){setError(e.message ?? 'Unable to sign in.');} finally{setBusy(false);} };
 return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Rider Companion</Text><Text style={styles.subtitle}>{register?'Create your rider account':'Welcome back'}</Text>{register&&<><TextInput placeholder="First name" value={firstName} onChangeText={setFirstName} style={styles.input}/><TextInput placeholder="Last name" value={lastName} onChangeText={setLastName} style={styles.input}/></>}<TextInput autoCapitalize="none" keyboardType="email-address" placeholder="Email" value={email} onChangeText={setEmail} style={styles.input}/><TextInput secureTextEntry placeholder="Password (8+ characters)" value={password} onChangeText={setPassword} style={styles.input}/>{error?<Text style={styles.error}>{error}</Text>:null}<Button title={busy?'Please wait…':register?'Create account':'Sign in'} onPress={submit} disabled={busy}/><Text style={styles.link} onPress={()=>setRegister(!register)}>{register?'Already have an account? Sign in':'New rider? Create an account'}</Text></ScrollView>;
}
export const styles=StyleSheet.create({page:{flexGrow:1,justifyContent:'center',padding:24,gap:12,backgroundColor:'#f7f8fa'},title:{fontSize:30,fontWeight:'700',color:'#172033'},subtitle:{fontSize:16,marginBottom:16},input:{backgroundColor:'white',borderWidth:1,borderColor:'#c9cdd4',padding:14,borderRadius:8,fontSize:16},error:{color:'#b42318'},link:{textAlign:'center',color:'#155eef',marginTop:8}});
